### ISSUE TITLE
Upgrade symfony/http-client package for Laravel v7.0 and above

### ISSUE THREAD

**Issue by tosinibrahim96** [engage-so/engage-php#2]
## Detailed Description
My team has been using the `engage-php` package with Laravel and we really want to commend you on the work you are doing. Thank you!  The current version of the package uses `symfony/http-client` version "4.4" to manage HTTP requests internally and we would appreciate it if the `http-client` package can be upgraded to version 5 of Symfony.

## Context
My team is trying to upgrade our Laravel version from Laravel 5.8 which uses the 4.x series of the Symfony components to a more recent version of Laravel (7.0 - 8.75.0) which utilize the 5.x series of the Symfony components.  The upgrade process cannot be completed since engage-php requires a 4.x version of a Symfony component (`http-client` specifically). 

Many Laravel projects today will be using the higher versions (7&8), so using `engage-php` will become a problem when they try to add the package to their project.

## Possible Implementation
Upgrade `symfony/http-client` package to version ^5.x 

## Environment
* Laravel Version: ^7.0
* PHP Version: 7.2.5

**Comment by kehers** [comment]
Thanks a lot for the detailed breakdown. We will get on this asap.

**Comment by tosinibrahim96** [comment]
Hi @kehers , I just wanted to confirm if there's any progress on this yet. Thanks

**Comment by afolabiabass** [comment]
https://github.com/engage-so/engage-php/pull/3 This PR is now opened to address this.

**Comment by kehers** [comment]
Merged 0a8ef180606c7d352b6b947cea52be6773de696e

**Comment by kehers** [comment]
Merged 0a8ef180606c7d352b6b947cea52be6773de696e
